version: '3.9'
services:
    server:
        build: $PWD/.docker/server
        container_name: "${PROJECT_NAME}_server"
        restart: always
        volumes:
            - $PWD/html:/var/www/html
        ports:
            - "${HTTP_PORT}:80"
        networks:
            - LAMP
        depends_on: 
            - db
    
    db:
        image: mariadb:10.5
        container_name: "${PROJECT_NAME}_db"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
            MYSQL_DATABASE: "${DB_NAME}"
        ports:
            - "${DB_PORT_EXT}:3306"
        networks:
            - LAMP
        volumes:
            - $PWD/.docker/mysql:/var/lib/mysql

networks:
    LAMP: